send:
  - method: 'GET'
    url: 'tango/console'

  - method: 'GET'
    url: 'tango/rest'

detect:
  - response:
    - headers:
      - 'WWW-Authenticate': 'Basic realm="TangoREST"'

meta-info:
  - type: info
  - threat: 25
  - applicable_for:
    - fast
    - scanner
  - tags: 
    - TangoREST
    - Misconfiguration